/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

/*
	This is an optimized version of Dojo, built for deployment and not for
	development. To get sources and documentation, please visit:

		http://dojotoolkit.org
*/

//>>built
(function(b,l){var e,p=function(){},m=function(a){for(var c in a)return 0;return 1},r={}.toString,n=function(a){return"[object Function]"==r.call(a)},k=function(a){return"[object String]"==r.call(a)},h=function(a){return"[object Array]"==r.call(a)},a=function(a,c){if(a)for(var b=0;b<a.length;)c(a[b++])},f=function(a,c){for(var b in c)a[b]=c[b];return a},d=function(a,c){return f(Error(a),{src:"dojoLoader",info:c})},c=1,g=function(){return"_"+c++},q=function(a,c,b){return La(a,c,b,0,q)},u=this,v=u.document,
s=v&&v.createElement("DiV"),t=q.has=function(a){return n(y[a])?y[a]=y[a](u,v,s):y[a]},y=t.cache=l.hasCache;t.add=function(a,c,b,d){(void 0===y[a]||d)&&(y[a]=c);return b&&t(a)};t.add("host-webworker","undefined"!==typeof WorkerGlobalScope&&self instanceof WorkerGlobalScope);t("host-webworker")&&(f(l.hasCache,{"host-browser":0,dom:0,"dojo-dom-ready-api":0,"dojo-sniff":0,"dojo-inject-api":1,"host-webworker":1}),l.loaderPatch={injectUrl:function(a,c){try{importScripts(a),c()}catch(b){console.error(b)}}});
for(var A in b.has)t.add(A,b.has[A],0,1);var w=0,F=[],x=0,C=p,I=p,O;q.isXdUrl=p;q.initSyncLoader=function(a,c,b){x||(x=a,C=c,I=b);return{sync:"sync",requested:1,arrived:2,nonmodule:3,executing:4,executed:5,syncExecStack:F,modules:z,execQ:Q,getModule:X,injectModule:pa,setArrived:ca,signal:D,finishExec:ga,execModule:ha,dojoRequirePlugin:x,getLegacyMode:function(){return w},guardCheckComplete:ia}};var P=location.protocol,K=location.host;q.isXdUrl=function(a){return/^\./.test(a)?!1:/^\/\//.test(a)?!0:
(a=a.match(/^([^\/\:]+\:)\/+([^\/]+)/))&&(a[1]!=P||K&&a[2]!=K)};t.add("dojo-force-activex-xhr",!v.addEventListener&&"file:"==window.location.protocol);t.add("native-xhr","undefined"!=typeof XMLHttpRequest);if(t("native-xhr")&&!t("dojo-force-activex-xhr"))O=function(){return new XMLHttpRequest};else{var S=["Msxml2.XMLHTTP","Microsoft.XMLHTTP","Msxml2.XMLHTTP.4.0"],B;for(e=0;3>e;)try{if(B=S[e++],new ActiveXObject(B))break}catch(G){}O=function(){return new ActiveXObject(B)}}q.getXhr=O;t.add("dojo-gettext-api",
1);q.getText=function(a,c,b){var f=O();f.open("GET",qa(a),!1);f.send(null);if(200==f.status||!location.host&&!f.status)b&&b(f.responseText,c);else throw d("xhrFailed",f.status);return f.responseText};var M=new Function("return eval(arguments[0]);");q.eval=function(a,c){return M(a+"\r\n//# sourceURL\x3d"+c)};var E={},D=q.signal=function(c,b){var d=E[c];a(d&&d.slice(0),function(a){a.apply(null,h(b)?b:[b])})},N=q.on=function(a,c){var b=E[a]||(E[a]=[]);b.push(c);return{remove:function(){for(var a=0;a<
b.length;a++)if(b[a]===c){b.splice(a,1);break}}}},da=[],Y={},$=[],L={},J=q.map={},T=[],z={},H="",V={},U={},ea={},W=0,ra=function(a){var c,b,d,f;for(c in U)b=U[c],(d=c.match(/^url\:(.+)/))?V["url:"+Ma(d[1],a)]=b:"*now"==c?f=b:"*noref"!=c&&(d=ja(c,a,!0),V[d.mid]=V["url:"+d.url]=b);f&&f(Ba(a));U={}},Na=function(a){return a.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,function(a){return"\\"+a})},Ca=function(a,c){c.splice(0,c.length);for(var b in a)c.push([b,a[b],RegExp("^"+Na(b)+"(/|$)"),b.length]);c.sort(function(a,
c){return c[3]-a[3]});return c},$a=function(c,b){a(c,function(a){b.push([k(a[0])?RegExp("^"+Na(a[0])+"$"):a[0],a[1]])})},Oa=function(a){var c=a.name;c||(c=a,a={name:c});a=f({main:"main"},a);a.location=a.location?a.location:c;a.packageMap&&(J[c]=a.packageMap);a.main.indexOf("./")||(a.main=a.main.substring(2));L[c]=a},Pa=[],ka=function(c,b,d){for(var g in c){"waitSeconds"==g&&(q.waitms=1E3*(c[g]||0));"cacheBust"==g&&(H=c[g]?k(c[g])?c[g]:(new Date).getTime()+"":"");if("baseUrl"==g||"combo"==g)q[g]=c[g];
if("async"==g){var h=c[g];q.legacyMode=w=k(h)&&/sync|legacyAsync/.test(h)?h:!h?"sync":!1;q.async=!w}c[g]!==y&&(q.rawConfig[g]=c[g],"has"!=g&&t.add("config-"+g,c[g],0,b))}q.baseUrl||(q.baseUrl="./");/\/$/.test(q.baseUrl)||(q.baseUrl+="/");for(g in c.has)t.add(g,c.has[g],0,b);a(c.packages,Oa);for(var r in c.packagePaths)a(c.packagePaths[r],function(a){var c=r+"/"+a;k(a)&&(a={name:a});a.location=c;Oa(a)});Ca(f(J,c.map),T);a(T,function(a){a[1]=Ca(a[1],[]);"*"==a[0]&&(T.star=a)});Ca(f(Y,c.paths),$);$a(c.aliases,
da);if(b)Pa.push({config:c.config});else for(g in c.config)b=X(g,d),b.config=f(b.config||{},c.config[g]);c.cache&&(ra(),U=c.cache,c.cache["*noref"]&&ra());D("config",[c,q.rawConfig])};t("dojo-cdn");var sa=v.getElementsByTagName("script");e=0;for(var Z,ba,ta,la;e<sa.length;){Z=sa[e++];if((ta=Z.getAttribute("src"))&&(la=ta.match(/(((.*)\/)|^)dojo\.js(\W|$)/i)))ba=la[3]||"",l.baseUrl=l.baseUrl||ba,W=Z;if(ta=Z.getAttribute("data-dojo-config")||Z.getAttribute("djConfig"))ea=q.eval("({ "+ta+" })","data-dojo-config"),
W=Z}q.rawConfig={};ka(l,1);t("dojo-cdn")&&((L.dojo.location=ba)&&(ba+="/"),L.dijit.location=ba+"../dijit/",L.dojox.location=ba+"../dojox/");ka(b,1);ka(ea,1);var ma=function(c){ia(function(){a(c.deps,pa)})},La=function(a,c,b,t,r){var e;if(k(a)){if((e=X(a,t,!0))&&e.executed)return e.result;throw d("undefinedModule",a);}h(a)||(ka(a,0,t),a=c,c=b);if(h(a))if(a.length){b="require*"+g();for(var n,m=[],u=0;u<a.length;)n=a[u++],m.push(X(n,t));e=f(ua("",b,0,""),{injected:2,deps:m,def:c||p,require:t?t.require:
q,gc:1});z[e.mid]=e;ma(e);var s=na&&"sync"!=w;ia(function(){ha(e,s)});e.executed||Q.push(e);fa()}else c&&c();return r},Ba=function(a){if(!a)return q;var c=a.require;c||(c=function(b,d,f){return La(b,d,f,a,c)},a.require=f(c,q),c.module=a,c.toUrl=function(c){return Ma(c,a)},c.toAbsMid=function(c){return Da(c,a)},c.syncLoadNls=function(c){c=ja(c,a);var b=z[c.mid];if(!b||!b.executed)if(aa=V[c.mid]||V["url:"+c.url])va(aa),b=z[c.mid];return b&&b.executed&&b.result});return c},Q=[],wa=[],R={},ab=function(a){a.injected=
1;R[a.mid]=1;a.url&&(R[a.url]=a.pack||1);Qa()},ca=function(a){a.injected=2;delete R[a.mid];a.url&&delete R[a.url];m(R)&&(xa(),"xd"==w&&(w="sync"))},bb=q.idle=function(){return!wa.length&&m(R)&&!Q.length&&!na},Ea=function(a,c){if(c)for(var b=0;b<c.length;b++)if(c[b][2].test(a))return c[b];return 0},Ra=function(a){var c=[],b,d;for(a=a.replace(/\\/g,"/").split("/");a.length;)b=a.shift(),".."==b&&c.length&&".."!=d?(c.pop(),d=c[c.length-1]):"."!=b&&c.push(d=b);return c.join("/")},ua=function(a,c,b,d){var f=
q.isXdUrl(d);return{pid:a,mid:c,pack:b,url:d,executed:0,def:0,isXd:f,isAmd:!!(f||L[a]&&L[a].isAmd)}},Sa=function(c,b,f,g,q,h,r,e,k){var m,u,s,y;y=/^\./.test(c);if(/(^\/)|(\:)|(\.js$)/.test(c)||y&&!b)return ua(0,c,0,c);c=Ra(y?b.mid+"/../"+c:c);if(/^\./.test(c))throw d("irrationalPath",c);b&&(s=Ea(b.mid,h));(s=(s=s||h.star)&&Ea(c,s[1]))&&(c=s[1]+c.substring(s[3]));b=(la=c.match(/^([^\/]+)(\/(.+))?$/))?la[1]:"";(m=f[b])?c=b+"/"+(u=la[3]||m.main):b="";var p=0;a(e,function(a){var b=c.match(a[0]);b&&0<
b.length&&(p=n(a[1])?c.replace(a[0],a[1]):a[1])});if(p)return Sa(p,0,f,g,q,h,r,e,k);if(f=g[c])return k?ua(f.pid,f.mid,f.pack,f.url):g[c];g=(s=Ea(c,r))?s[1]+c.substring(s[3]):b?m.location+"/"+u:t("config-tlmSiblingOfDojo")?"../"+c:c;/(^\/)|(\:)/.test(g)||(g=q+g);return ua(b,c,m,Ra(g+".js"))},ja=function(a,c,b){return Sa(a,c,L,z,q.baseUrl,b?[]:T,b?[]:$,b?[]:da)},Ta=function(a,c,b){return a.normalize?a.normalize(c,function(a){return Da(a,b)}):Da(c,b)},Ua=0,X=function(a,c,b){var d,f;(d=a.match(/^(.+?)\!(.*)$/))?
(f=X(d[1],c,b),"sync"==w&&!f.executed&&(pa(f),2===f.injected&&!f.executed&&ia(function(){ha(f)}),f.executed?ya(f):Q.unshift(f)),5===f.executed&&!f.load&&ya(f),f.load?(d=Ta(f,d[2],c),a=f.mid+"!"+(f.dynamic?++Ua+"!":"")+d):(d=d[2],a=f.mid+"!"+ ++Ua+"!waitingForPlugin"),a={plugin:f,mid:a,req:Ba(c),prid:d}):a=ja(a,c);return z[a.mid]||!b&&(z[a.mid]=a)},Da=q.toAbsMid=function(a,c){return ja(a,c).mid},Ma=q.toUrl=function(a,c){var b=ja(a+"/x",c),f=b.url;return qa(0===b.pid?a:f.substring(0,f.length-5))},Va=
{injected:2,executed:5,def:3,result:3},Fa=function(a){return z[a]=f({mid:a},Va)},cb=Fa("require"),db=Fa("exports"),eb=Fa("module"),za={},Ga=0,ya=function(a){var c=a.result;a.dynamic=c.dynamic;a.normalize=c.normalize;a.load=c.load;return a},fb=function(c){var b={};a(c.loadQ,function(a){var d=Ta(c,a.prid,a.req.module),g=c.dynamic?a.mid.replace(/waitingForPlugin$/,d):c.mid+"!"+d,d=f(f({},a),{mid:g,prid:d,injected:0});z[g]||Wa(z[g]=d);b[a.mid]=z[g];ca(a);delete z[a.mid]});c.loadQ=0;var d=function(a){for(var c=
a.deps||[],d=0;d<c.length;d++)(a=b[c[d].mid])&&(c[d]=a)},g;for(g in z)d(z[g]);a(Q,d)},ga=function(c){q.trace("loader-finish-exec",[c.mid]);c.executed=5;c.defOrder=Ga++;a(c.provides,function(a){a()});c.loadQ&&(ya(c),fb(c));for(e=0;e<Q.length;)Q[e]===c?Q.splice(e,1):e++;/^require\*/.test(c.mid)&&delete z[c.mid]},gb=[],ha=function(a,c){if(4===a.executed)return q.trace("loader-circular-dependency",[gb.concat(a.mid).join("-\x3e")]),!a.def||c?za:a.cjs&&a.cjs.exports;if(!a.executed){if(!a.def)return za;
var b=a.mid,f=a.deps||[],g,h=[],r=0;for(a.executed=4;g=f[r++];){g=g===cb?Ba(a):g===db?a.cjs.exports:g===eb?a.cjs:ha(g,c);if(g===za)return a.executed=0,q.trace("loader-exec-module",["abort",b]),za;h.push(g)}q.trace("loader-run-factory",[a.mid]);var b=a.def,e;F.unshift(a);if(t("config-dojo-loader-catches"))try{e=n(b)?b.apply(null,h):b}catch(k){D("error",a.result=d("factoryThrew",[a,k]))}else e=n(b)?b.apply(null,h):b;a.result=void 0===e&&a.cjs?a.cjs.exports:e;F.shift(a);ga(a)}return a.result},na=0,ia=
function(a){try{na++,a()}finally{na--}bb()&&D("idle",[])},fa=function(){na||ia(function(){C();for(var a,c,b=0;b<Q.length;)a=Ga,c=Q[b],ha(c),a!=Ga?(C(),b=0):b++})};void 0===t("dojo-loader-eval-hint-url")&&t.add("dojo-loader-eval-hint-url",1);var qa="function"==typeof b.fixupUrl?b.fixupUrl:function(a){a+="";return a+(H?(/\?/.test(a)?"\x26":"?")+H:"")},Wa=function(a){var c=a.plugin;5===c.executed&&!c.load&&ya(c);var b=function(c){a.result=c;ca(a);ga(a);fa()};c.load?c.load(a.prid,a.req,b):c.loadQ?c.loadQ.push(a):
(c.loadQ=[a],Q.unshift(c),pa(c))},aa=0,oa=0,Ha=0,va=function(a,c){t("config-stripStrict")&&(a=a.replace(/"use strict"/g,""));Ha=1;if(t("config-dojo-loader-catches"))try{a===aa?aa.call(null):q.eval(a,t("dojo-loader-eval-hint-url")?c.url:c.mid)}catch(b){D("error",d("evalModuleThrew",c))}else a===aa?aa.call(null):q.eval(a,t("dojo-loader-eval-hint-url")?c.url:c.mid);Ha=0},pa=function(c){var b=c.mid,g=c.url;if(!c.executed&&!c.injected&&!(R[b]||c.url&&(c.pack&&R[c.url]===c.pack||1==R[c.url])))if(ab(c),
c.plugin)Wa(c);else{var h=function(){Xa(c);if(2!==c.injected){if(t("dojo-enforceDefine")){D("error",d("noDefine",c));return}ca(c);f(c,Va);q.trace("loader-define-nonmodule",[c.url])}w?!F.length&&fa():fa()};if(aa=V[b]||V["url:"+c.url])q.trace("loader-inject",["cache",c.mid,g]),va(aa,c),h();else{if(w)if(c.isXd)"sync"==w&&(w="xd");else if(!(c.isAmd&&"sync"!=w)){var r=function(d){if("sync"==w){F.unshift(c);va(d,c);F.shift();Xa(c);c.cjs||(ca(c),ga(c));if(c.finish){d=b+"*finish";var f=c.finish;delete c.finish;
Ia(d,["dojo",("dojo/require!"+f.join(",")).replace(/\./g,"/")],function(c){a(f,function(a){c.require(a)})});Q.unshift(X(d))}h()}else(d=I(c,d))?(va(d,c),h()):(oa=c,q.injectUrl(qa(g),h,c),oa=0)};q.trace("loader-inject",["xhr",c.mid,g,"sync"!=w]);if(t("config-dojo-loader-catches"))try{q.getText(g,"sync"!=w,r)}catch(e){D("error",d("xhrInjectFailed",[c,e]))}else q.getText(g,"sync"!=w,r);return}q.trace("loader-inject",["script",c.mid,g]);oa=c;q.injectUrl(qa(g),h,c);oa=0}}},Ja=function(a,c,b){q.trace("loader-define-module",
[a.mid,c]);var g=a.mid;if(2===a.injected)return D("error",d("multipleDefine",a)),a;f(a,{deps:c,def:b,cjs:{id:a.mid,uri:a.url,exports:a.result={},setExports:function(c){a.cjs.exports=c},config:function(){return a.config}}});for(var t=0;c[t];t++)c[t]=X(c[t],a);w&&!R[g]&&(ma(a),Q.push(a),fa());ca(a);!n(b)&&!c.length&&(a.result=b,ga(a));return a},Xa=function(c,b){for(var d=[],f,g;wa.length;)g=wa.shift(),b&&(g[0]=b.shift()),f=g[0]&&X(g[0])||c,d.push([f,g[1],g[2]]);ra(c);a(d,function(a){ma(Ja.apply(null,
a))})},Aa=0,xa=p,Qa=p,xa=function(){Aa&&clearTimeout(Aa);Aa=0},Qa=function(){xa();q.waitms&&(Aa=u.setTimeout(function(){xa();D("error",d("timeout",R))},q.waitms))};t.add("ie-event-behavior",v.attachEvent&&"undefined"===typeof Windows&&("undefined"===typeof opera||"[object Opera]"!=opera.toString()));var Ka=function(a,c,b,d){if(t("ie-event-behavior"))return a.attachEvent(b,d),function(){a.detachEvent(b,d)};a.addEventListener(c,d,!1);return function(){a.removeEventListener(c,d,!1)}},hb=Ka(window,"load",
"onload",function(){q.pageLoaded=1;"complete"!=v.readyState&&(v.readyState="complete");hb()}),sa=v.getElementsByTagName("script");for(e=0;!W;)if(!/^dojo/.test((Z=sa[e++])&&Z.type))W=Z;q.injectUrl=function(a,c,b){b=b.node=v.createElement("script");var f=Ka(b,"load","onreadystatechange",function(a){a=a||window.event;var b=a.target||a.srcElement;if("load"===a.type||/complete|loaded/.test(b.readyState))f(),g(),c&&c()}),g=Ka(b,"error","onerror",function(c){f();g();D("error",d("scriptError",[a,c]))});b.type=
"text/javascript";b.charset="utf-8";b.src=a;W.parentNode.insertBefore(b,W);return b};q.log=function(){try{for(var a=0;a<arguments.length;a++);}catch(c){}};q.trace=p;var Ia=function(a,c,b){var f=arguments.length,g=["require","exports","module"],h=[0,a,c];1==f?h=[0,n(a)?g:[],a]:2==f&&k(a)?h=[a,n(c)?g:[],c]:3==f&&(h=[a,c,b]);q.trace("loader-define",h.slice(0,2));if((f=h[0]&&X(h[0]))&&!R[f.mid])ma(Ja(f,h[1],h[2]));else if(!t("ie-event-behavior")||Ha)wa.push(h);else{f=f||oa;if(!f)for(a in R)if((g=z[a])&&
g.node&&"interactive"===g.node.readyState){f=g;break}f?(ra(f),ma(Ja(f,h[1],h[2]))):D("error",d("ieDefineFailed",h[0]));fa()}};Ia.amd={vendor:"dojotoolkit.org"};f(f(q,l.loaderPatch),b.loaderPatch);N("error",function(a){try{if(console.error(a),a instanceof Error)for(var c in a);}catch(b){}});f(q,{uid:g,cache:V,packs:L});if(u.define)D("error",d("defineAlreadyDefined",0));else{u.define=Ia;u.require=q;a(Pa,function(a){ka(a)});var Ya=ea.deps||b.deps||l.deps,Za=ea.callback||b.callback||l.callback;q.boot=
Ya||Za?[Ya||[],Za]:0}})(this.dojoConfig||this.djConfig||this.require||{},{async:"legacyAsync",hasCache:{"config-selectorEngine":"acme","config-tlmSiblingOfDojo":1,"dojo-built":1,"dojo-cdn":1,"dojo-loader":1,dom:1,"host-browser":1},packages:[{location:"../dijit",name:"dijit"},{location:"../dojox",name:"dojox"},{location:".",name:"dojo"}]});
require({cache:{"dojo/request/default":function(){define(["exports","require","../has"],function(b,l,e){var p=e("config-requestProvider");p||(p="./xhr");b.getPlatformDefaultId=function(){return"./xhr"};b.load=function(b,r,e,k){l(["platform"==b?"./xhr":p],function(b){e(b)})}})},"dojo/_base/fx":function(){define("./kernel ./config ./lang ../Evented ./Color ../aspect ../sniff ../dom ../dom-style".split(" "),function(b,l,e,p,m,r,n,k,h){var a=e.mixin,f={},d=f._Line=function(a,c){this.start=a;this.end=
c};d.prototype.getValue=function(a){return(this.end-this.start)*a+this.start};var c=f.Animation=function(c){a(this,c);e.isArray(this.curve)&&(this.curve=new d(this.curve[0],this.curve[1]))};c.prototype=new p;e.extend(c,{duration:350,repeat:0,rate:20,_percent:0,_startRepeatCount:0,_getStep:function(){var a=this._percent,c=this.easing;return c?c(a):a},_fire:function(a,c){var b=c||[];if(this[a])if(l.debugAtAllCosts)this[a].apply(this,b);else try{this[a].apply(this,b)}catch(d){console.error("exception in animation handler for:",
a),console.error(d)}return this},play:function(a,c){this._delayTimer&&this._clearTimer();if(c)this._stopTimer(),this._active=this._paused=!1,this._percent=0;else if(this._active&&!this._paused)return this;this._fire("beforeBegin",[this.node]);var b=a||this.delay,d=e.hitch(this,"_play",c);if(0<b)return this._delayTimer=setTimeout(d,b),this;d();return this},_play:function(a){this._delayTimer&&this._clearTimer();this._startTime=(new Date).valueOf();this._paused&&(this._startTime-=this.duration*this._percent);
this._active=!0;this._paused=!1;a=this.curve.getValue(this._getStep());this._percent||(this._startRepeatCount||(this._startRepeatCount=this.repeat),this._fire("onBegin",[a]));this._fire("onPlay",[a]);this._cycle();return this},pause:function(){this._delayTimer&&this._clearTimer();this._stopTimer();if(!this._active)return this;this._paused=!0;this._fire("onPause",[this.curve.getValue(this._getStep())]);return this},gotoPercent:function(a,c){this._stopTimer();this._active=this._paused=!0;this._percent=
a;c&&this.play();return this},stop:function(a){this._delayTimer&&this._clearTimer();if(!this._timer)return this;this._stopTimer();a&&(this._percent=1);this._fire("onStop",[this.curve.getValue(this._getStep())]);this._active=this._paused=!1;return this},destroy:function(){this.stop()},status:function(){return this._active?this._paused?"paused":"playing":"stopped"},_cycle:function(){if(this._active){var a=(new Date).valueOf(),a=0===this.duration?1:(a-this._startTime)/this.duration;1<=a&&(a=1);this._percent=
a;this.easing&&(a=this.easing(a));this._fire("onAnimate",[this.curve.getValue(a)]);1>this._percent?this._startTimer():(this._active=!1,0<this.repeat?(this.repeat--,this.play(null,!0)):-1==this.repeat?this.play(null,!0):this._startRepeatCount&&(this.repeat=this._startRepeatCount,this._startRepeatCount=0),this._percent=0,this._fire("onEnd",[this.node]),!this.repeat&&this._stopTimer())}return this},_clearTimer:function(){clearTimeout(this._delayTimer);delete this._delayTimer}});var g=0,q=null,u={run:function(){}};
e.extend(c,{_startTimer:function(){this._timer||(this._timer=r.after(u,"run",e.hitch(this,"_cycle"),!0),g++);q||(q=setInterval(e.hitch(u,"run"),this.rate))},_stopTimer:function(){this._timer&&(this._timer.remove(),this._timer=null,g--);0>=g&&(clearInterval(q),q=null,g=0)}});var v=n("ie")?function(a){var c=a.style;!c.width.length&&"auto"==h.get(a,"width")&&(c.width="auto")}:function(){};f._fade=function(c){c.node=k.byId(c.node);var b=a({properties:{}},c);c=b.properties.opacity={};c.start=!("start"in
b)?function(){return+h.get(b.node,"opacity")||0}:b.start;c.end=b.end;c=f.animateProperty(b);r.after(c,"beforeBegin",e.partial(v,b.node),!0);return c};f.fadeIn=function(c){return f._fade(a({end:1},c))};f.fadeOut=function(c){return f._fade(a({end:0},c))};f._defaultEasing=function(a){return 0.5+Math.sin((a+1.5)*Math.PI)/2};var s=function(a){this._properties=a;for(var c in a){var b=a[c];b.start instanceof m&&(b.tempColor=new m)}};s.prototype.getValue=function(a){var c={},b;for(b in this._properties){var d=
this._properties[b],f=d.start;f instanceof m?c[b]=m.blendColors(f,d.end,a,d.tempColor).toCss():e.isArray(f)||(c[b]=(d.end-f)*a+f+("opacity"!=b?d.units||"px":0))}return c};f.animateProperty=function(d){var f=d.node=k.byId(d.node);d.easing||(d.easing=b._defaultEasing);d=new c(d);r.after(d,"beforeBegin",e.hitch(d,function(){var c={},b;for(b in this.properties){if("width"==b||"height"==b)this.node.display="block";var d=this.properties[b];e.isFunction(d)&&(d=d(f));d=c[b]=a({},e.isObject(d)?d:{end:d});
e.isFunction(d.start)&&(d.start=d.start(f));e.isFunction(d.end)&&(d.end=d.end(f));var g=0<=b.toLowerCase().indexOf("color"),q=function(a,c){var b={height:a.offsetHeight,width:a.offsetWidth}[c];if(void 0!==b)return b;b=h.get(a,c);return"opacity"==c?+b:g?b:parseFloat(b)};"end"in d?"start"in d||(d.start=q(f,b)):d.end=q(f,b);g?(d.start=new m(d.start),d.end=new m(d.end)):d.start="opacity"==b?+d.start:parseFloat(d.start)}this.curve=new s(c)}),!0);r.after(d,"onAnimate",e.hitch(h,"set",d.node),!0);return d};
f.anim=function(a,b,d,g,h,q){return f.animateProperty({node:a,duration:d||c.prototype.duration,properties:b,easing:g,onEnd:h}).play(q||0)};a(b,f);b._Animation=c;return f})},"dojo/dom-form":function(){define(["./_base/lang","./dom","./io-query","./json"],function(b,l,e,p){var m={fieldToObject:function(b){var e=null;if(b=l.byId(b)){var k=b.name,h=(b.type||"").toLowerCase();if(k&&h&&!b.disabled)if("radio"==h||"checkbox"==h)b.checked&&(e=b.value);else if(b.multiple){e=[];for(b=[b.firstChild];b.length;)for(k=
b.pop();k;k=k.nextSibling)if(1==k.nodeType&&"option"==k.tagName.toLowerCase())k.selected&&e.push(k.value);else{k.nextSibling&&b.push(k.nextSibling);k.firstChild&&b.push(k.firstChild);break}}else e=b.value}return e},toObject:function(e){var n={};e=l.byId(e).elements;for(var k=0,h=e.length;k<h;++k){var a=e[k],f=a.name,d=(a.type||"").toLowerCase();if(f&&d&&0>"file|submit|image|reset|button".indexOf(d)&&!a.disabled){var c=n,g=f,a=m.fieldToObject(a);if(null!==a){var q=c[g];"string"==typeof q?c[g]=[q,a]:
b.isArray(q)?q.push(a):c[g]=a}"image"==d&&(n[f+".x"]=n[f+".y"]=n[f].x=n[f].y=0)}}return n},toQuery:function(b){return e.objectToQuery(m.toObject(b))},toJson:function(b,e){return p.stringify(m.toObject(b),null,e?4:0)}};return m})},"dojo/i18n":function(){define("./_base/kernel require ./has ./_base/array ./_base/config ./_base/lang ./_base/xhr ./json module".split(" "),function(b,l,e,p,m,r,n,k,h){e.add("dojo-preload-i18n-Api",1);var a=b.i18n={},f=/(^.*(^|\/)nls)(\/|$)([^\/]*)\/?([^\/]*)/,d=function(a,
c,b,d){var f=[b+d];c=c.split("-");for(var g="",h=0;h<c.length;h++)if(g+=(g?"-":"")+c[h],!a||a[g])f.push(b+g+"/"+d),f.specificity=g;return f},c={},g=function(a,c,d){d=d?d.toLowerCase():b.locale;a=a.replace(/\./g,"/");c=c.replace(/\./g,"/");return/root/i.test(d)?a+"/nls/"+c:a+"/nls/"+d+"/"+c},q=b.getL10nName=function(a,c,b){return h.id+"!"+g(a,c,b)},u=function(a,b,f,g,h,q){a([b],function(e){var k=r.clone(e.root||e.ROOT),m=d(!e._v1x&&e,h,f,g);a(m,function(){for(var a=1;a<m.length;a++)k=r.mixin(r.clone(k),
arguments[a]);c[b+"/"+h]=k;k.$locale=m.specificity;q()})})},v=function(a){var c=m.extraLocale||[],c=r.isArray(c)?c:[c];c.push(a);return c},s=function(a,d,g){if(e("dojo-preload-i18n-Api")){var h=a.split("*"),q="preload"==h[1];q&&(c[a]||(c[a]=1,F(h[2],k.parse(h[3]),1,d)),g(1));if(!(h=q))A&&w.push([a,d,g]),h=A;if(h)return}a=f.exec(a);var m=a[1]+"/",t=a[5]||a[4],n=m+t,h=(a=a[5]&&a[4])||b.locale||"",s=n+"/"+h;a=a?[h]:v(h);var l=a.length,y=function(){--l||g(r.delegate(c[s]))};p.forEach(a,function(a){var b=
n+"/"+a;e("dojo-preload-i18n-Api")&&x(b);c[b]?y():u(d,n,m,t,a,y)})};if(e("dojo-unit-tests"))var t=a.unitTests=[];e("dojo-preload-i18n-Api");var y=a.normalizeLocale=function(a){a=a?a.toLowerCase():b.locale;return"root"==a?"ROOT":a},A=0,w=[],F=a._preloadLocalizations=function(a,d,f,g){function h(a,c){g.isXdUrl(l.toUrl(a+".js"))||f?g([a],c):O([a],c,g)}function q(a,c){for(var b=a.split("-");b.length;){if(c(b.join("-")))return;b.pop()}c("ROOT")}function e(){for(--A;!A&&w.length;)s.apply(null,w.shift())}
function k(b){b=y(b);q(b,function(f){if(0<=p.indexOf(d,f)){var k=a.replace(/\./g,"/")+"_"+f;A++;h(k,function(a){for(var d in a){var h=a[d],k=d.match(/(.+)\/([^\/]+)$/),m;if(k){m=k[2];k=k[1]+"/";h._localized=h._localized||{};var t;if("ROOT"===f){var n=t=h._localized;delete h._localized;n.root=h;c[l.toAbsMid(d)]=n}else t=h._localized,c[l.toAbsMid(k+m+"/"+f)]=h;f!==b&&function(a,d,f,h){var k=[],m=[];q(b,function(c){h[c]&&(k.push(l.toAbsMid(a+c+"/"+d)),m.push(l.toAbsMid(a+d+"/"+c)))});k.length?(A++,g(k,
function(){for(var g=0;g<k.length;g++)f=r.mixin(r.clone(f),arguments[g]),c[m[g]]=f;c[l.toAbsMid(a+d+"/"+b)]=r.clone(f);e()})):c[l.toAbsMid(a+d+"/"+b)]=f}(k,m,h,t)}}e()});return!0}return!1})}g=g||l;k();p.forEach(b.config.extraLocale,k)},x=function(){},C={},I=new Function("__bundle","__checkForLegacyModules","__mid","__amdValue","var define \x3d function(mid, factory){define.called \x3d 1; __amdValue.result \x3d factory || mid;},\t   require \x3d function(){define.called \x3d 1;};try{define.called \x3d 0;eval(__bundle);if(define.called\x3d\x3d1)return __amdValue;if((__checkForLegacyModules \x3d __checkForLegacyModules(__mid)))return __checkForLegacyModules;}catch(e){}try{return eval('('+__bundle+')');}catch(e){return e;}"),
O=function(a,b,d){var f=[];p.forEach(a,function(a){function b(d){d=I(d,x,a,C);d===C?f.push(c[g]=C.result):(d instanceof Error&&(console.error("failed to evaluate i18n bundle; url\x3d"+g,d),d={}),f.push(c[g]=/nls\/[^\/]+\/[^\/]+$/.test(g)?d:{root:d,_v1x:1}))}var g=d.toUrl(a+".js");if(c[g])f.push(c[g]);else{var h=d.syncLoadNls(a);if(h)f.push(h);else if(n)n.get({url:g,sync:!0,load:b,error:function(){f.push(c[g]={})}});else try{d.getText(g,!0,b)}catch(q){f.push(c[g]={})}}});b&&b.apply(null,f)},x=function(a){for(var d,
f=a.split("/"),g=b.global[f[0]],h=1;g&&h<f.length-1;g=g[f[h++]]);g&&((d=g[f[h]])||(d=g[f[h].replace(/-/g,"_")]),d&&(c[a]=d));return d};a.getLocalization=function(a,c,b){var d;a=g(a,c,b);s(a,!l.isXdUrl(l.toUrl(a+".js"))?function(a,c){O(a,c,l)}:l,function(a){d=a});return d};e("dojo-unit-tests")&&t.push(function(a){a.register("tests.i18n.unit",function(a){var c;c=I("{prop:1}",x,"nonsense",C);a.is({prop:1},c);a.is(void 0,c[1]);c=I("({prop:1})",x,"nonsense",C);a.is({prop:1},c);a.is(void 0,c[1]);c=I("{'prop-x':1}",
x,"nonsense",C);a.is({"prop-x":1},c);a.is(void 0,c[1]);c=I("({'prop-x':1})",x,"nonsense",C);a.is({"prop-x":1},c);a.is(void 0,c[1]);c=I("define({'prop-x':1})",x,"nonsense",C);a.is(C,c);a.is({"prop-x":1},C.result);c=I("define('some/module', {'prop-x':1})",x,"nonsense",C);a.is(C,c);a.is({"prop-x":1},C.result);c=I("this is total nonsense and should throw an error",x,"nonsense",C);a.is(c instanceof Error,!0)})});return r.mixin(a,{dynamic:!0,normalize:function(a,c){return/^\./.test(a)?c(a):a},load:s,cache:c,
getL10nName:q})})},"dojo/promise/tracer":function(){define(["../_base/lang","./Promise","../Evented"],function(b,l,e){function p(b){setTimeout(function(){r.apply(m,b)},0)}var m=new e,r=m.emit;m.emit=null;l.prototype.trace=function(){var e=b._toArray(arguments);this.then(function(b){p(["resolved",b].concat(e))},function(b){p(["rejected",b].concat(e))},function(b){p(["progress",b].concat(e))});return this};l.prototype.traceRejected=function(){var e=b._toArray(arguments);this.otherwise(function(b){p(["rejected",
b].concat(e))});return this};return m})},"dojo/errors/RequestError":function(){define(["./create"],function(b){return b("RequestError",function(b,e){this.response=e})})},"dojo/_base/html":function(){define("./kernel ../dom ../dom-style ../dom-attr ../dom-prop ../dom-class ../dom-construct ../dom-geometry".split(" "),function(b,l,e,p,m,r,n,k){b.byId=l.byId;b.isDescendant=l.isDescendant;b.setSelectable=l.setSelectable;b.getAttr=p.get;b.setAttr=p.set;b.hasAttr=p.has;b.removeAttr=p.remove;b.getNodeProp=
p.getNodeProp;b.attr=function(b,a,f){return 2==arguments.length?p["string"==typeof a?"get":"set"](b,a):p.set(b,a,f)};b.hasClass=r.contains;b.addClass=r.add;b.removeClass=r.remove;b.toggleClass=r.toggle;b.replaceClass=r.replace;b._toDom=b.toDom=n.toDom;b.place=n.place;b.create=n.create;b.empty=function(b){n.empty(b)};b._destroyElement=b.destroy=function(b){n.destroy(b)};b._getPadExtents=b.getPadExtents=k.getPadExtents;b._getBorderExtents=b.getBorderExtents=k.getBorderExtents;b._getPadBorderExtents=
b.getPadBorderExtents=k.getPadBorderExtents;b._getMarginExtents=b.getMarginExtents=k.getMarginExtents;b._getMarginSize=b.getMarginSize=k.getMarginSize;b._getMarginBox=b.getMarginBox=k.getMarginBox;b.setMarginBox=k.setMarginBox;b._getContentBox=b.getContentBox=k.getContentBox;b.setContentSize=k.setContentSize;b._isBodyLtr=b.isBodyLtr=k.isBodyLtr;b._docScroll=b.docScroll=k.docScroll;b._getIeDocumentElementOffset=b.getIeDocumentElementOffset=k.getIeDocumentElementOffset;b._fixIeBiDiScrollLeft=b.fixIeBiDiScrollLeft=
k.fixIeBiDiScrollLeft;b.position=k.position;b.marginBox=function(b,a){return a?k.setMarginBox(b,a):k.getMarginBox(b)};b.contentBox=function(b,a){return a?k.setContentSize(b,a):k.getContentBox(b)};b.coords=function(h,a){b.deprecated("dojo.coords()","Use dojo.position() or dojo.marginBox().");h=l.byId(h);var f=e.getComputedStyle(h),f=k.getMarginBox(h,f),d=k.position(h,a);f.x=d.x;f.y=d.y;return f};b.getProp=m.get;b.setProp=m.set;b.prop=function(b,a,f){return 2==arguments.length?m["string"==typeof a?
"get":"set"](b,a):m.set(b,a,f)};b.getStyle=e.get;b.setStyle=e.set;b.getComputedStyle=e.getComputedStyle;b.__toPixelValue=b.toPixelValue=e.toPixelValue;b.style=function(b,a,f){switch(arguments.length){case 1:return e.get(b);case 2:return e["string"==typeof a?"get":"set"](b,a)}return e.set(b,a,f)};return b})},"dojo/_base/kernel":function(){define(["../has","./config","require","module"],function(b,l,e,p){var m,r;m=function(){return this}();var n={},k={},h={config:l,global:m,dijit:n,dojox:k},n={dojo:["dojo",
h],dijit:["dijit",n],dojox:["dojox",k]};p=e.map&&e.map[p.id.match(/[^\/]+/)[0]];for(r in p)n[r]?n[r][0]=p[r]:n[r]=[p[r],{}];for(r in n)p=n[r],p[1]._scopeName=p[0],l.noGlobals||(m[p[0]]=p[1]);h.scopeMap=n;h.baseUrl=h.config.baseUrl=e.baseUrl;h.isAsync=e.async;h.locale=l.locale;m="$Rev: f4fef70 $".match(/[0-9a-f]{7,}/);h.version={major:1,minor:10,patch:4,flag:"",revision:m?m[0]:NaN,toString:function(){var a=h.version;return a.major+"."+a.minor+"."+a.patch+a.flag+" ("+a.revision+")"}};Function("d","d.eval \x3d function(){return d.global.eval ? d.global.eval(arguments[0]) : eval(arguments[0]);}")(h);
h.exit=function(){};"undefined"!=typeof console||(console={});p="assert count debug dir dirxml error group groupEnd info profile profileEnd time timeEnd trace warn log".split(" ");var a;for(m=0;a=p[m++];)console[a]||function(){var b=a+"";console[b]="log"in console?function(){var a=Array.prototype.slice.call(arguments);a.unshift(b+":");console.log(a.join(" "))}:function(){};console[b]._fake=!0}();b.add("dojo-debug-messages",!!l.isDebug);h.deprecated=h.experimental=function(){};b("dojo-debug-messages")&&
(h.deprecated=function(a,b,c){a="DEPRECATED: "+a;b&&(a+=" "+b);c&&(a+=" -- will be removed in version: "+c);console.warn(a)},h.experimental=function(a,b){var c="EXPERIMENTAL: "+a+" -- APIs subject to change without notice.";b&&(c+=" "+b);console.warn(c)});if(l.modulePaths){h.deprecated("dojo.modulePaths","use paths configuration");b={};for(r in l.modulePaths)b[r.replace(/\./g,"/")]=l.modulePaths[r];e({paths:b})}h.moduleUrl=function(a,b){h.deprecated("dojo.moduleUrl()","use require.toUrl","2.0");var c=
null;a&&(c=e.toUrl(a.replace(/\./g,"/")+(b?"/"+b:"")+"/*.*").replace(/\/\*\.\*/,"")+(b?"":"/"));return c};h._hasResource={};return h})},"dojo/io-query":function(){define(["./_base/lang"],function(b){var l={};return{objectToQuery:function(e){var p=encodeURIComponent,m=[],r;for(r in e){var n=e[r];if(n!=l[r]){var k=p(r)+"\x3d";if(b.isArray(n))for(var h=0,a=n.length;h<a;++h)m.push(k+p(n[h]));else m.push(k+p(n))}}return m.join("\x26")},queryToObject:function(e){var p=decodeURIComponent;e=e.split("\x26");
for(var m={},r,n,k=0,h=e.length;k<h;++k)if(n=e[k],n.length){var a=n.indexOf("\x3d");0>a?(r=p(n),n=""):(r=p(n.slice(0,a)),n=p(n.slice(a+1)));"string"==typeof m[r]&&(m[r]=[m[r]]);b.isArray(m[r])?m[r].push(n):m[r]=n}return m}}})},"dojo/_base/Deferred":function(){define("./kernel ../Deferred ../promise/Promise ../errors/CancelError ../has ./lang ../when".split(" "),function(b,l,e,p,m,r,n){var k=function(){},h=Object.freeze||function(){},a=b.Deferred=function(b){function d(a){if(q)throw Error("This deferred has already been resolved");
g=a;q=!0;c()}function c(){for(var a;!a&&y;){var c=y;y=y.next;if(a=c.progress==k)q=!1;var b=s?c.error:c.resolved;m("config-useDeferredInstrumentation")&&s&&l.instrumentRejected&&l.instrumentRejected(g,!!b);if(b)try{var d=b(g);d&&"function"===typeof d.then?d.then(r.hitch(c.deferred,"resolve"),r.hitch(c.deferred,"reject"),r.hitch(c.deferred,"progress")):(b=a&&void 0===d,a&&!b&&(s=d instanceof Error),c.deferred[b&&s?"reject":"resolve"](b?g:d))}catch(f){c.deferred.reject(f)}else s?c.deferred.reject(g):
c.deferred.resolve(g)}}var g,q,u,n,s,t,y,A=this.promise=new e;this.isResolved=A.isResolved=function(){return 0==n};this.isRejected=A.isRejected=function(){return 1==n};this.isFulfilled=A.isFulfilled=function(){return 0<=n};this.isCanceled=A.isCanceled=function(){return u};this.resolve=this.callback=function(a){this.fired=n=0;this.results=[a,null];d(a)};this.reject=this.errback=function(a){s=!0;this.fired=n=1;m("config-useDeferredInstrumentation")&&l.instrumentRejected&&l.instrumentRejected(a,!!y);
d(a);this.results=[null,a]};this.progress=function(a){for(var c=y;c;){var b=c.progress;b&&b(a);c=c.next}};this.addCallbacks=function(a,c){this.then(a,c,k);return this};A.then=this.then=function(b,d,f){var g=f==k?this:new a(A.cancel);b={resolved:b,error:d,progress:f,deferred:g};y?t=t.next=b:y=t=b;q&&c();return g.promise};var w=this;A.cancel=this.cancel=function(){if(!q){var a=b&&b(w);q||(a instanceof Error||(a=new p(a)),a.log=!1,w.reject(a))}u=!0};h(A)};r.extend(a,{addCallback:function(a){return this.addCallbacks(r.hitch.apply(b,
arguments))},addErrback:function(a){return this.addCallbacks(null,r.hitch.apply(b,arguments))},addBoth:function(a){var d=r.hitch.apply(b,arguments);return this.addCallbacks(d,d)},fired:-1});a.when=b.when=n;return a})},"dojo/NodeList-dom":function(){define("./_base/kernel ./query ./_base/array ./_base/lang ./dom-class ./dom-construct ./dom-geometry ./dom-attr ./dom-style".split(" "),function(b,l,e,p,m,r,n,k,h){function a(a){return function(c,b,d){return 2==arguments.length?a["string"==typeof b?"get":
"set"](c,b):a.set(c,b,d)}}var f=function(a){return 1==a.length&&"string"==typeof a[0]},d=function(a){var c=a.parentNode;c&&c.removeChild(a)},c=l.NodeList,g=c._adaptWithCondition,q=c._adaptAsForEach,u=c._adaptAsMap;p.extend(c,{_normalize:function(a,c){var d=!0===a.parse;if("string"==typeof a.template){var f=a.templateFunc||b.string&&b.string.substitute;a=f?f(a.template,a):a}f=typeof a;"string"==f||"number"==f?(a=r.toDom(a,c&&c.ownerDocument),a=11==a.nodeType?p._toArray(a.childNodes):[a]):p.isArrayLike(a)?
p.isArray(a)||(a=p._toArray(a)):a=[a];d&&(a._runParse=!0);return a},_cloneNode:function(a){return a.cloneNode(!0)},_place:function(a,c,d,f){if(!(1!=c.nodeType&&"only"==d))for(var g,h=a.length,q=h-1;0<=q;q--){var e=f?this._cloneNode(a[q]):a[q];if(a._runParse&&b.parser&&b.parser.parse){g||(g=c.ownerDocument.createElement("div"));g.appendChild(e);b.parser.parse(g);for(e=g.firstChild;g.firstChild;)g.removeChild(g.firstChild)}q==h-1?r.place(e,c,d):c.parentNode.insertBefore(e,c);c=e}},position:u(n.position),
attr:g(a(k),f),style:g(a(h),f),addClass:q(m.add),removeClass:q(m.remove),toggleClass:q(m.toggle),replaceClass:q(m.replace),empty:q(r.empty),removeAttr:q(k.remove),marginBox:u(n.getMarginBox),place:function(a,c){var b=l(a)[0];return this.forEach(function(a){r.place(a,b,c)})},orphan:function(a){return(a?l._filterResult(this,a):this).forEach(d)},adopt:function(a,c){return l(a).place(this[0],c)._stash(this)},query:function(a){if(!a)return this;var b=new c;this.map(function(c){l(a,c).forEach(function(a){void 0!==
a&&b.push(a)})});return b._stash(this)},filter:function(a){var c=arguments,b=this,d=0;if("string"==typeof a){b=l._filterResult(this,c[0]);if(1==c.length)return b._stash(this);d=1}return this._wrap(e.filter(b,c[d],c[d+1]),this)},addContent:function(a,c){a=this._normalize(a,this[0]);for(var b=0,d;d=this[b];b++)a.length?this._place(a,d,c,0<b):r.empty(d);return this}});return c})},"dojo/query":function(){define("./_base/kernel ./has ./dom ./on ./_base/array ./_base/lang ./selector/_loader ./selector/_loader!default".split(" "),
function(b,l,e,p,m,r,n,k){function h(a,c){var b=function(b,d){if("string"==typeof d&&(d=e.byId(d),!d))return new c([]);var f="string"==typeof b?a(b,d):b?b.end&&b.on?b:[b]:[];return f.end&&f.on?f:new c(f)};b.matches=a.match||function(a,c,d){return 0<b.filter([a],c,d).length};b.filter=a.filter||function(a,c,d){return b(c,d).filter(function(c){return-1<m.indexOf(a,c)})};if("function"!=typeof a){var d=a.search;a=function(a,c){return d(c||document,a)}}return b}l.add("array-extensible",function(){return 1==
r.delegate([],{length:1}).length&&!l("bug-for-in-skips-shadowed")});var a=Array.prototype,f=a.slice,d=a.concat,c=m.forEach,g=function(a,c,d){c=[0].concat(f.call(c,0));d=d||b.global;return function(b){c[0]=b;return a.apply(d,c)}},q=function(a){var c=this instanceof u&&l("array-extensible");"number"==typeof a&&(a=Array(a));var b=a&&"length"in a?a:arguments;if(c||!b.sort){for(var d=c?this:[],f=d.length=b.length,g=0;g<f;g++)d[g]=b[g];if(c)return d;b=d}r._mixin(b,v);b._NodeListCtor=function(a){return u(a)};
return b},u=q,v=u.prototype=l("array-extensible")?[]:{};u._wrap=v._wrap=function(a,c,b){a=new (b||this._NodeListCtor||u)(a);return c?a._stash(c):a};u._adaptAsMap=function(a,c){return function(){return this.map(g(a,arguments,c))}};u._adaptAsForEach=function(a,c){return function(){this.forEach(g(a,arguments,c));return this}};u._adaptAsFilter=function(a,c){return function(){return this.filter(g(a,arguments,c))}};u._adaptWithCondition=function(a,c,d){return function(){var f=arguments,h=g(a,f,d);if(c.call(d||
b.global,f))return this.map(h);this.forEach(h);return this}};c(["slice","splice"],function(c){var b=a[c];v[c]=function(){return this._wrap(b.apply(this,arguments),"slice"==c?this:null)}});c(["indexOf","lastIndexOf","every","some"],function(a){var c=m[a];v[a]=function(){return c.apply(b,[this].concat(f.call(arguments,0)))}});r.extend(q,{constructor:u,_NodeListCtor:u,toString:function(){return this.join(",")},_stash:function(a){this._parent=a;return this},on:function(a,c){var b=this.map(function(b){return p(b,
a,c)});b.remove=function(){for(var a=0;a<b.length;a++)b[a].remove()};return b},end:function(){return this._parent?this._parent:new this._NodeListCtor(0)},concat:function(a){var c=f.call(this,0),b=m.map(arguments,function(a){return f.call(a,0)});return this._wrap(d.apply(c,b),this)},map:function(a,c){return this._wrap(m.map(this,a,c),this)},forEach:function(a,b){c(this,a,b);return this},filter:function(a){var c=arguments,b=this,d=0;if("string"==typeof a){b=s._filterResult(this,c[0]);if(1==c.length)return b._stash(this);
d=1}return this._wrap(m.filter(b,c[d],c[d+1]),this)},instantiate:function(a,c){var b=r.isFunction(a)?a:r.getObject(a);c=c||{};return this.forEach(function(a){new b(c,a)})},at:function(){var a=new this._NodeListCtor(0);c(arguments,function(c){0>c&&(c=this.length+c);this[c]&&a.push(this[c])},this);return a._stash(this)}});var s=h(k,q);b.query=h(k,function(a){return q(a)});s.load=function(a,c,b){n.load(a,c,function(a){b(h(a,q))})};b._filterQueryResult=s._filterResult=function(a,c,b){return new q(s.filter(a,
c,b))};b.NodeList=s.NodeList=q;return s})},"dojo/has":function(){define(["require","module"],function(b,l){var e=b.has||function(){};e.add("dom-addeventlistener",!!document.addEventListener);e.add("touch","ontouchstart"in document||"onpointerdown"in document&&0<navigator.maxTouchPoints||window.navigator.msMaxTouchPoints);e.add("touch-events","ontouchstart"in document);e.add("pointer-events","onpointerdown"in document);e.add("MSPointer","msMaxTouchPoints"in navigator);e.add("device-width",screen.availWidth||
innerWidth);var p=document.createElement("form");e.add("dom-attributes-explicit",0==p.attributes.length);e.add("dom-attributes-specified-flag",0<p.attributes.length&&40>p.attributes.length);e.clearElement=function(b){b.innerHTML="";return b};e.normalize=function(b,r){var n=b.match(/[\?:]|[^:\?]*/g),k=0,h=function(a){var b=n[k++];if(":"==b)return 0;if("?"==n[k++]){if(!a&&e(b))return h();h(!0);return h(a)}return b||0};return(b=h())&&r(b)};e.load=function(b,e,n){b?e([b],n):n()};return e})},"dojo/_base/loader":function(){define("./kernel ../has require module ../json ./lang ./array".split(" "),
function(b,l,e,p,m,r,n){var k=function(a){return a.replace(/\./g,"/")},h=/\/\/>>built/,a=[],f=[],d=function(b,d,g){a.push(g);n.forEach(b.split(","),function(a){a=K(a,d.module);f.push(a);S(a)});c()},c=function(){var c,b;for(b in O)if(c=O[b],void 0===c.noReqPluginCheck&&(c.noReqPluginCheck=/loadInit\!/.test(b)||/require\!/.test(b)?1:0),!c.executed&&!c.noReqPluginCheck&&c.injected==A)return;N(function(){var c=a;a=[];n.forEach(c,function(a){a(1)})})},g=function(a,c,d){var f=/\(|\)/g,g=1;for(f.lastIndex=
c;(c=f.exec(a))&&!(g=")"==c[0]?g-1:g+1,0==g););if(0!=g)throw"unmatched paren around character "+f.lastIndex+" in: "+a;return[b.trim(a.substring(d,f.lastIndex))+";\n",f.lastIndex]},q=/(\/\*([\s\S]*?)\*\/|\/\/(.*)$)/mg,u=/(^|\s)dojo\.(loadInit|require|provide|requireLocalization|requireIf|requireAfterIf|platformRequire)\s*\(/mg,v=/(^|\s)(require|define)\s*\(/m,s=function(a,c){var b,d,f,h=[],e=[];b=[];for(c=c||a.replace(q,function(a){u.lastIndex=v.lastIndex=0;return u.test(a)||v.test(a)?"":a});b=u.exec(c);)d=
u.lastIndex,f=d-b[0].length,d=g(c,d,f),"loadInit"==b[2]?h.push(d[0]):e.push(d[0]),u.lastIndex=d[1];b=h.concat(e);return b.length||!v.test(c)?[a.replace(/(^|\s)dojo\.loadInit\s*\(/g,"\n0 \x26\x26 dojo.loadInit("),b.join(""),b]:0},t=e.initSyncLoader(d,c,function(a,c){var b,d,f=[],g=[];if(h.test(c)||!(b=s(c)))return 0;d=a.mid+"-*loadInit";for(var e in K("dojo",a).result.scopeMap)f.push(e),g.push('"'+e+'"');return"// xdomain rewrite of "+a.mid+"\ndefine('"+d+"',{\n\tnames:"+m.stringify(f)+",\n\tdef:function("+
f.join(",")+"){"+b[1]+"}});\n\ndefine("+m.stringify(f.concat(["dojo/loadInit!"+d]))+", function("+f.join(",")+"){\n"+b[0]+"});"}),y=t.sync,A=t.requested,w=t.arrived,F=t.nonmodule,x=t.executing,C=t.executed,I=t.syncExecStack,O=t.modules,P=t.execQ,K=t.getModule,S=t.injectModule,B=t.setArrived,G=t.signal,M=t.finishExec,E=t.execModule,D=t.getLegacyMode,N=t.guardCheckComplete,d=t.dojoRequirePlugin;b.provide=function(a){var c=I[0],b=r.mixin(K(k(a),e.module),{executed:x,result:r.getObject(a,!0)});B(b);c&&
(c.provides||(c.provides=[])).push(function(){b.result=r.getObject(a);delete b.provides;b.executed!==C&&M(b)});return b.result};l.add("config-publishRequireResult",1,0,0);b.require=function(a,c){var b=function(a,c){var b=K(k(a),e.module);if(I.length&&I[0].finish)I[0].finish.push(a);else{if(b.executed)return b.result;c&&(b.result=F);var d=D();S(b);d=D();b.executed!==C&&b.injected===w&&t.guardCheckComplete(function(){E(b)});if(b.executed)return b.result;d==y?b.cjs?P.unshift(b):I.length&&(I[0].finish=
[a]):P.push(b)}}(a,c);l("config-publishRequireResult")&&(!r.exists(a)&&void 0!==b)&&r.setObject(a,b);return b};b.loadInit=function(a){a()};b.registerModulePath=function(a,c){var b={};b[a.replace(/\./g,"/")]=c;e({paths:b})};b.platformRequire=function(a){a=(a.common||[]).concat(a[b._name]||a["default"]||[]);for(var c;a.length;)r.isArray(c=a.shift())?b.require.apply(b,c):b.require(c)};b.requireIf=b.requireAfterIf=function(a,c,d){a&&b.require(c,d)};b.requireLocalization=function(a,c,b){e(["../i18n"],
function(d){d.getLocalization(a,c,b)})};return{extractLegacyApiApplications:s,require:d,loadInit:function(a,c,f){c([a],function(a){c(a.names,function(){for(var g="",h=[],e=0;e<arguments.length;e++)g+="var "+a.names[e]+"\x3d arguments["+e+"]; ",h.push(arguments[e]);eval(g);var q=c.module,r=[],m,g={provide:function(a){a=k(a);a=K(a,q);a!==q&&B(a)},require:function(a,c){a=k(a);c&&(K(a,q).result=F);r.push(a)},requireLocalization:function(a,c,d){m||(m=["dojo/i18n"]);d=(d||b.locale).toLowerCase();a=k(a)+
"/nls/"+(/root/i.test(d)?"":d+"/")+k(c);K(a,q).isXd&&m.push("dojo/i18n!"+a)},loadInit:function(a){a()}},e={},n;try{for(n in g)e[n]=b[n],b[n]=g[n];a.def.apply(null,h)}catch(u){G("error",[{src:p.id,id:"failedDojoLoadInit"},u])}finally{for(n in g)b[n]=e[n]}m&&(r=r.concat(m));r.length?d(r.join(","),c,f):f()})})}}})},"dojo/json":function(){define(["./has"],function(b){var l="undefined"!=typeof JSON;b.add("json-parse",l);b.add("json-stringify",l&&'{"a":1}'==JSON.stringify({a:0},function(b,e){return e||
1}));if(b("json-stringify"))return JSON;var e=function(b){return('"'+b.replace(/(["\\])/g,"\\$1")+'"').replace(/[\f]/g,"\\f").replace(/[\b]/g,"\\b").replace(/[\n]/g,"\\n").replace(/[\t]/g,"\\t").replace(/[\r]/g,"\\r")};return{parse:b("json-parse")?JSON.parse:function(b,e){if(e&&!/^([\s\[\{]*(?:"(?:\\.|[^"])*"|-?\d[\d\.]*(?:[Ee][+-]?\d+)?|null|true|false|)[\s\]\}]*(?:,|:|$))+$/.test(b))throw new SyntaxError("Invalid characters in JSON");return eval("("+b+")")},stringify:function(b,m,r){function n(b,
a,f){m&&(b=m(f,b));var 